Homework day7 collections
Volha95/Volha_Gardzeyeva_AT_G7 pull request #14
Opened 2023-03-21 13:25 UTC by Volha95

2023-03-21 16:55 UTC, AlexKapylov requested changes

2023-03-21 16:55 UTC, AlexKapylov commented on src/main/java/homework/day7/ButterfliesList.java
> +        for (String butterfly : butterflies) {
Здесь можно сделать эффективнее. Просто загугли, увидишь, что ничего сложного.

2023-03-21 16:55 UTC, AlexKapylov commented on src/main/java/homework/day7/CarsList.java
> +        try {
Переделай. Если вдруг возникнет exception, то ты обработаешь его, но поток закрыт не будет. Нам показывали метод записи, в котором без указания закрытия потока, поток будет закрываться.

2023-03-21 16:55 UTC, AlexKapylov commented on src/main/java/homework/day7/CarsList.java
> +            for (String car : cars) {
Подебажь здесь. Непонятно зачем ты делаешь два цикла, можно обойтись одним, тогда, вероятнее всего, и обработки exception'a не потребуется.

2023-03-21 16:55 UTC, AlexKapylov commented on src/main/java/homework/day7/CitiesList.java
> +        for (String city : cities) {
Много лишних телодвижений. Все намного проще. Исправь.

2023-03-21 16:55 UTC, AlexKapylov commented on src/main/java/homework/day7/DoublesList.java
> +        for (Double doubl : doubles) {
Здесь у тебя сумма частей после запятой получается больше, чем сумма этих чисел с их целой частью)) не забывай, что нужно получить не сумму чисел 42 + 3 + 79 +... , а сумму чисел 0.42 + 0.3 + 0.79 + ... . Исправь.

2023-03-21 16:55 UTC, AlexKapylov commented on src/main/java/homework/day7/ElementsList.java
> +                if (element.charAt(i) == ' ' || element.charAt(i) == '-') {
Решение для частного случая. А что если там появится элемент состоящий из двух слов, в котором второе слово будет в скобках?. Исправь. (через регулярки)

2023-03-21 16:55 UTC, AlexKapylov commented on src/main/java/homework/day7/FiguresList.java
> +        try {
Переделай. Если вдруг возникнет exception, то ты обработаешь его, но поток закрыт не будет. Нам показывали метод записи, в котором без указания закрытия потока, поток будет закрываться.

2023-03-21 16:55 UTC, AlexKapylov commented on src/main/java/homework/day7/FiguresList.java
> +        figures.set(2, "Треугольник");
Здесь ты заменяешь третью позицию, а в задании написано "Вставить на 3 позицию"

2023-03-21 16:55 UTC, AlexKapylov commented on src/main/java/homework/day7/NumbersList.java
> +        for (Integer number : numbers) {
можно просто int

2023-03-21 16:55 UTC, AlexKapylov commented on src/main/java/homework/day7/NumbersList.java
> +        for (Integer number : numbers) {
можно просто int

2023-03-21 16:55 UTC, AlexKapylov commented on src/main/java/homework/day7/NumbersList.java
> +            for (int i = 0; i < number; i++) {
Зачем так усложнять, нельзя ли просто складывать элементы списка?)

2023-03-21 16:55 UTC, AlexKapylov commented on src/main/java/homework/day7/NumbersList.java
> +        for (Integer number : numbers) {
можно просто int

2023-03-23 14:02 UTC, Volha95 commented on src/main/java/homework/day7/ElementsList.java
> +                if (element.charAt(i) == ' ' || element.charAt(i) == '-') {
corrected)

2023-03-23 18:05 UTC, AlexKapylov requested changes

2023-03-23 18:05 UTC, AlexKapylov commented on src/main/java/homework/day7/CarsList.java
> +                out.write("\"" + car + "\"\n");
" - " забыла

2023-03-23 18:21 UTC, AlexKapylov approved these changes

2023-03-23 18:22 UTC, merged