added homework day 8 Person
Volha95/Volha_Gardzeyeva_AT_G7 pull request #16
Opened 2023-03-25 13:47 UTC by Volha95

2023-03-25 17:36 UTC, AlexKapylov requested changes

2023-03-25 17:36 UTC, AlexKapylov commented on src/main/java/homework/day8/PersonList.java
> +        System.out.println(people.stream().filter(person -> person.age > 18 && person.age < 55 && person.sex.equals(Person.Sex.WOMEN) || person.age > 18 && person.age < 60 && person.sex.equals(Person
здесь либо исправь все на ">=", либо цифры поменяй. потому что сейчас у тебя, например, 18, не включительно, а должно быть включительно

2023-03-25 17:36 UTC, AlexKapylov commented on src/main/java/homework/day8/PersonList.java
> +            if (person.age > 18 && person.age < 55 && person.sex.equals(Person.Sex.WOMEN) || person.age > 18 && person.age < 60 && person.sex.equals(Person.Sex.MAN)) {
здесь либо исправь все на ">=", либо цифры поменяй. потому что сейчас у тебя, например, 18, не включительно, а должно быть включительно

2023-03-25 21:02 UTC, Volha95 commented on src/main/java/homework/day8/PersonList.java
> +        System.out.println(people.stream().filter(person -> person.age > 18 && person.age < 55 && person.sex.equals(Person.Sex.WOMEN) || person.age > 18 && person.age < 60 && person.sex.equals(Person
corrected

2023-03-25 21:02 UTC, Volha95 commented on src/main/java/homework/day8/PersonList.java
> +            if (person.age > 18 && person.age < 55 && person.sex.equals(Person.Sex.WOMEN) || person.age > 18 && person.age < 60 && person.sex.equals(Person.Sex.MAN)) {
corrected

2023-03-26 09:14 UTC, AlexKapylov approved these changes

2023-03-26 09:30 UTC, merged