Homework day9 streams
Volha95/Volha_Gardzeyeva_AT_G7 pull request #19
Opened 2023-03-31 18:06 UTC by Volha95

2023-04-02 09:40 UTC, AlexKapylov requested changes

2023-04-02 09:40 UTC, AlexKapylov commented on src/main/java/homework/day9/DoublesRunner.java
> +                .map(s -> (int) (Math.random() * s.intValue()))
насколько я знаю условие задания не такое

2023-04-02 09:40 UTC, AlexKapylov commented on src/main/java/homework/day9/DoublesRunner.java
> +                .map(s -> new Bubble(s, "Bubble vol-" + s))
насколько я знаю условие задания не такое

2023-04-02 09:40 UTC, AlexKapylov commented on src/main/java/homework/day9/NumbersModRunner.java
> +                            for (char c = '0'; c <= '9'; ++c)
честно говоря я не совсем понимаю как ты тут работаешь не переводя чары в инт, но результат у тебя неправильно отсортирован в итоге)

2023-04-02 09:40 UTC, AlexKapylov commented on src/main/java/homework/day9/WaterRunner.java
> +                    if (s.getSmell().contains("ы")) {
if можно не писать, сразу нужный return

2023-04-03 10:33 UTC, Volha95 commented on src/main/java/homework/day9/DoublesRunner.java
> +                .map(s -> (int) (Math.random() * s.intValue()))
corrected

2023-04-03 17:40 UTC, AlexKapylov approved these changes

2023-04-03 17:41 UTC, merged